apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  type: NodePort
  selector:
    app: nginx-ingress
    component: controller
  ports:
    - name: http
      nodePort: 8088
      port: 8088
      targetPort: http
      protocol: TCP

